language: ruby

services:
  - docker

before_install:
  - docker build -t abidex4yemi/react-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true abidex4yemi/react-docker npm run test -- --coverage
