language: ruby

services:
  - docker

before_install:
  - docker build -t abidex4yemi/react-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true abidex4yemi/react-docker npm run test -- --coverage

deploy:
  provider: 'elasticbeanstalk'
  region: 'us-east-2'
  app: 'docker-frontend'
  env: 'DockerFrontend-env'
  bucket_name: 'elasticbeanstalk-us-east-2-918123694774'
  path_name: 'docker-frontend'
  on:
    branch: master
  access_key_id: '$AWS_ACCESS_KEY'
  secret_access_key:
    secure: '$AWS_SECRET_ACCESS_KEY'
